// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cedoifdkvlxuaawdmtld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZG9pZmRrdmx4dWFhd2RtdGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODQxNDgsImV4cCI6MjA3Mzk2MDE0OH0.E-lUyga-C7oF7VcXqjh7jrZkqKSwjuuxxuOZmq-cNKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});